import turtle
b=turtle.Screen()
b.bgcolor("red")
a=turtle.Turtle()
a.speed(0.5)
a.begin_fill()
# a.fd(100)
# a.left(90)
# a.fd(100)
# a.left(90)
# a.fd(100)
# a.left(90)
# a.forward(100)
for i in range(4):
    a.fd(100)
    a.left(90)
a.end_fill()
a.hideturtle()
turtle.mainloop()